version: "3.8"

services:
  flask-middleware:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=http://0.0.0.0:11434
      - OLLAMA_CONTEXT_LENGTH=4096
    networks:
      - app-network

volumes:
  ollama_data:

networks:
  app-network:
    driver: bridge
