version: "3.8"

services:
  # Flask middleware application
  flask-middleware:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DEBUG=False
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=llama2
      - OLLAMA_TIMEOUT=30
      - MAX_CONCURRENT_OLLAMA=3
    depends_on:
      - ollama
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "2"

  # Ollama service
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./ollama-models:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 12G # Adjust based on your model size
          cpus: "8" # Adjust based on your hardware

networks:
  app-network:
    driver: bridge
